### ISSUE TITLE
青龙运行出错V2.11.1,以及请问token文件格式是怎么填写的呢

### ISSUE THREAD

**Issue by qqeeg** [Charles-Hello/didi_all_in#1]
Traceback (most recent call last):
  File "maomao_didi_ql.py", line 153, in main
    self.initialize(d)
AttributeError: 'Msg' object has no attribute 'initialize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maomao_didi_ql.py", line 153, in main
    self.initialize(d)
AttributeError: 'Msg' object has no attribute 'initialize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maomao_didi_ql.py", line 153, in main
    self.initialize(d)
AttributeError: 'Msg' object has no attribute 'initialize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maomao_didi_ql.py", line 153, in main
    self.initialize(d)
AttributeError: 'Msg' object has no attribute 'initialize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maomao_didi_ql.py", line 153, in main
    self.initialize(d)
AttributeError: 'Msg' object has no attribute 'initialize'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "maomao_didi_ql.py", line 165, in <module>
    Msg().main()  # 初始化通知服务
  File "maomao_didi_ql.py", line 160, in main
    return self.main(f)
  File "maomao_didi_ql.py", line 160, in main
    return self.main(f)
  File "maomao_didi_ql.py", line 160, in main
    return self.main(f)
  [Previous line repeated 1 more time]
  File "maomao_didi_ql.py", line 162, in main
    msg('获取通知服务失败，请检查网络连接...')
NameError: name 'msg' is not defined

**Comment by yuzhilz** [comment]
同问，大佬脚本token格式什么样，放这里面/ql/config/djangolog/diditoken.txt吗？

**Comment by Charles-Hello** [comment]
拉库没有拉到通知文件！

**Comment by Charles-Hello** [comment]
> 

是的。具体看我写的正则吧！

**Comment by Charles-Hello** [comment]
@qqeeg 拉库没有拉到通知文件！再次拉取吧

**Comment by yuzhilz** [comment]
> @qqeeg 拉库没有拉到通知文件！再次拉取吧

大佬，抓那里的token，能给个token格式样板吗
运行日志提示 共0滴滴盲盒个账号Cookie

**Comment by Charles-Hello** [comment]
@yuzhilz 你看readme吧，我刚刚更了格式！

**Comment by yuzhilz** [comment]
> @yuzhilz 你看readme吧，我刚刚更了格式！

谢谢大佬
